---
spring:
  application:
    name: GarageDoorOpener
  output:
    ansi:
      enabled: ALWAYS
#server:
  #context-path: /
  #port: 8080
# logging:
  # level:
    # org.dronezone.keycode: DEBUG
    #org.springframework.security: DEBUG

garage:
  door:
    keycode-secret: '0228'